### ISSUE TITLE
Give please an example

### ISSUE THREAD

**Issue by ArtemLubimov** [jp9000/libdshowcapture#7]
Hi, how to work with this library, can you give some example or tutorial? Or how to scrren capture using this library?

**Comment by jp9000** [comment]
This library isn't used for capturing the screen.  It's used for capturing cameras or video capture devices.  I'll consider making an example at some point, but don't currently have time.  There's not much I can do about time unfortunately.

That being said, everything for using the library is in the dshowcapture.hpp header.  It's not too complex to use.

OBS Studio also uses this to its fullest extent, so you can also see how it's used there, but it's pretty extensive so it might seem a bit more complicated than it really is.
